/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "BLE_1_gatt.h"
#include "BLE_1.h"
#include "BLE_1_HAL_PVT.h"
#include "BLE_1_STACK_PVT.h"
#include "BLE_1_StackGap.h"
#include "BLE_1_StackGatt.h"
#include "BLE_1_StackGattDb.h"
#include "BLE_1_StackHostMain.h"
#include "BLE_1_StackL2cap.h"
#include "BLE_1_StackGattServer.h"
#include "BLE_1_StackGattClient.h"
#include "BLE_1_Stack.h"
#include "BLE_1_eventHandler.h"
#include "BLE_1_custom.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "isr_minute.h"
#include "Clock_1.h"
#include "ADC.h"
#include "temp_in.h"
#include "temp_in_aliases.h"
#include "Timer_minute.h"
#include "bat_in.h"
#include "bat_in_aliases.h"
#include "BAdvertLED.h"
#include "BAdvertLED_aliases.h"
#include "BLE_1_bless_isr.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

